services:
    Wandi\ColorPickerBundle\Twig\Extension\ColorExtension:
        tags:
            - { name: twig.extension }
    Wandi\ColorPickerBundle\Form\Type\ColorPickerType:
        arguments: ["@translator"]
        tags:
             - { name: form.type }
